spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}

app.admin.password=${APP_ADMIN_PASSWORD}
app.vet.password=${APP_VET_PASSWORD}
app.user.password=${APP_USER_PASSWORD}

app.cors.allowed-origin=${APP_CORS_ORIGIN}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never